### ISSUE TITLE
which pooling method is better when converting subword tokens to word tokens?

### ISSUE THREAD

**Issue by pangaass** [maltintas45/subtoken_level_2_token_level#1]
Thanks for your code . I have been working on it for a few days . I noticed you are gathering the first subword token from word tokens. Some code  provide several pooling methods to achieve that , such as first ,last ,max and mean . Which pooling method performs better when converting subword tokens to word tokens in your experiment ?

**Comment by maltintas45** [comment]
I think it depends the task that you want to do, but for me using the first is the best, because actually I never mind about this small difference :)

**Comment by maltintas45** [comment]
[This paper ](https://aclanthology.org/2021.eacl-main.194.pdf)compares them for three tasks. They show that the best one is using attention or LSTM over subwords. Thanks for your question.

**Comment by pangaass** [comment]
thank you for response,  that helps me a lot.
